name: Deploy to staging
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: https://staging.sovryn.app
    concurrency:
      group: Staging
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/erbium'
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@distributedcollective'

      - name: Install NPM dependencies
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_ACCESS_TOKEN }}

      - name: Build
        run: yarn build
        env:
          REACT_APP_NETWORK: 'mainnet'
          REACT_APP_STAGING: 'true'
          REACT_APP_BYPASS_MAINTENANCE: 'true'
          REACT_APP_ESTIMATOR_URI: 'https://simulator.sovryn.app'
          REACT_APP_INTERCOM_ID: 'zxxit1rp'
          REACT_APP_GRAPH_RSK: 'https://subgraph.sovryn.app/subgraphs/name/DistributedCollective/sovryn-subgraph'


      - name: Deploy to S3
        uses: raulanatol/aws-s3-docker-action@master
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          AWS_BUCKET_NAME:  '${{ secrets.AWS_S3_BUCKET }}'
          AWS_REGION: us-east-2
          SOURCE: build
#          TARGET:
          WITH_DELETE: true
#          WITH_CLOUD_FRONT_INVALIDATION:
#          AWS_CLOUDFRONT_DISTRIBUTION_ID:
#          AWS_CLOUDFRONT_INVALIDATION_PATH:
